apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  namespace: default
  labels:
    app: nginx-web
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: A1
    cis.f5.com/as3-pool: web_pool
spec:
  ports:
  - name: nginx-web
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: nginx
